/// Traits applied to the owner mob when we turn into a deadite
GLOBAL_LIST_INIT(traits_deadite, list(
	TRAIT_NOMOOD,
	TRAIT_NOHUNGER,
	TRAIT_EASYDISMEMBER,
	TRAIT_NOBREATH,
	TRAIT_TOXIMMUNE,
	TRAIT_CHUNKYFINGERS,
	TRAIT_NOSLEEP,
	TRAIT_BASHDOORS,
	TRAIT_SPELLCOCKBLOCK,
	TRAIT_BLOODLOSS_IMMUNE,
	TRAIT_LIMPDICK,
	TRAIT_ZOMBIE_SPEECH,
	TRAIT_ZOMBIE_IMMUNE,
	TRAIT_NORUN
))

GLOBAL_LIST_INIT(intents_deadite, list(
	INTENT_HELP,
	INTENT_DISARM,
	INTENT_GRAB,
	INTENT_HARM
))
