environment = "roguetown.dme"

[langserver]
dreamchecker = true

[dmdoc]
use_typepath_names = true

[code_standards]
disallow_relative_type_definitions = false
disallow_relative_proc_definitions = false

[diagnostics]
# Raised by DreamChecker
disabled_directive = "off"
sets_directive_twice = "error"
invalid_lint_directive_value = "error"
invalid_set_value = "error"
unknown_linter_setting = "error"
override_missing_keyword_arg = "off"
must_not_override = "error"
must_call_parent = "off"
final_var = "error"
private_proc = "error"
protected_proc = "error"
private_var = "error"
protected_var = "error"
must_be_pure = "error"
must_not_sleep = "off"
redefined_proc = "off"
ambiguous_in_lhs = "off"
ambiguous_not_bitwise = "off"
no_typehint_implicit_new = "error"
field_access_static_type = "off"
proc_call_static_type = "off"
proc_has_no_parent = "error"
no_operator_overload = "off"
unreachable_code = "off"
control_condition_static = "error"
if_condition_determinate = "error"
loop_condition_determinate = "error"

[debugger]
engine = "auxtools"

[map_renderer.render_passes]
icon-smoothing = false
icon-smoothing-2016 = false
