#define SPELL_FIREBALL_old							/obj/effect/proc_holder/spell/aimed/fireball
#define SPELL_BLINDNESS_AOE							/obj/effect/proc_holder/spell/aoe_turf/blindness
#define SPELL_KNOCK									/obj/effect/proc_holder/spell/aoe_turf/knock
#define SPELL_REPULSE								/obj/effect/proc_holder/spell/aoe_turf/repulse	//This is the one we use.
#define SPELL_REPULSE_XENO							/obj/effect/proc_holder/spell/aoe_turf/repulse/xeno
#define SPELL_TIMESTOP								/obj/effect/proc_holder/spell/aoe_turf/timestop
#define SPELL_BLOODCRAWL							/obj/effect/proc_holder/spell/bloodcrawl
#define SPELL_ATTACH_BODYPART						/obj/effect/proc_holder/spell/invoked/attach_bodypart
#define SPELL_BLADE_BURST							/obj/effect/proc_holder/spell/invoked/blade_burst
#define SPELL_BLINDNESS								/obj/effect/proc_holder/spell/invoked/blindness
#define SPELL_BRIGHTEN								/obj/effect/proc_holder/spell/invoked/brighten
#define SPELL_BUD									/obj/effect/proc_holder/spell/invoked/bud
#define SPELL_BURDEN								/obj/effect/proc_holder/spell/invoked/burden
#define SPELL_CRAFTERCOVENANT						/obj/effect/proc_holder/spell/invoked/craftercovenant
#define SPELL_CURE_ROT								/obj/effect/proc_holder/spell/invoked/cure_rot
#define SPELL_DIAGNOSE								/obj/effect/proc_holder/spell/invoked/diagnose
#define SPELL_DIAGNOSE_SECULAR						/obj/effect/proc_holder/spell/invoked/diagnose/secular
#define SPELL_DRAIN_STAM							/obj/effect/proc_holder/spell/invoked/drain_stam
#define SPELL_EORACHARM								/obj/effect/proc_holder/spell/invoked/eoracharm
#define SPELL_EORACURSE								/obj/effect/proc_holder/spell/invoked/eoracurse
#define SPELL_EYEBITE								/obj/effect/proc_holder/spell/invoked/eyebite
#define SPELL_FEATHERFALL							/obj/effect/proc_holder/spell/invoked/featherfall
#define SPELL_FINDFAMILIAR							/obj/effect/proc_holder/spell/invoked/findfamiliar
#define SPELL_FORCEWALL_WEAK						/obj/effect/proc_holder/spell/invoked/forcewall_weak
#define SPELL_HAMMERFALL							/obj/effect/proc_holder/spell/invoked/hammerfall
#define SPELL_HASTE									/obj/effect/proc_holder/spell/invoked/haste
#define SPELL_ENLARGE								/obj/effect/proc_holder/spell/invoked/enlarge
#define SPELL_HEAL									/obj/effect/proc_holder/spell/invoked/heal
#define SPELL_HEATMETAL								/obj/effect/proc_holder/spell/invoked/heatmetal
#define SPELL_INVISIBILITY							/obj/effect/proc_holder/spell/invoked/invisibility
#define SPELL_JOINCOMRADES							/obj/effect/proc_holder/spell/invoked/joincomrades
#define SPELL_LEARNSPELL							/obj/effect/proc_holder/spell/invoked/learnspell
#define SPELL_LESSER_HEAL							/obj/effect/proc_holder/spell/invoked/lesser_heal
#define SPELL_MAGEBLINDNESS							/obj/effect/proc_holder/spell/invoked/mageblindness
#define SPELL_MAGEINVISIBILITY						/obj/effect/proc_holder/spell/invoked/mageinvisibility
#define SPELL_MALUM_FLAME_ROGUE						/obj/effect/proc_holder/spell/invoked/malum_flame_rogue
#define SPELL_MESSAGE								/obj/effect/proc_holder/spell/invoked/message
#define SPELL_PREPARE_FEAST							/obj/effect/proc_holder/spell/invoked/prepare_feast
#define SPELL_ANIMATE_OBJECT						/obj/effect/proc_holder/spell/invoked/projectile/animate_object
#define SPELL_ARCANEBOLT							/obj/effect/proc_holder/spell/invoked/projectile/arcanebolt
#define SPELL_BLOODLIGHTNING						/obj/effect/proc_holder/spell/invoked/projectile/bloodlightning
#define SPELL_BLOODSTEAL							/obj/effect/proc_holder/spell/invoked/projectile/bloodsteal
#define SPELL_FETCH									/obj/effect/proc_holder/spell/invoked/projectile/fetch
#define SPELL_FIREBALL								/obj/effect/proc_holder/spell/invoked/projectile/fireball
#define SPELL_FIREBALLGREATER						/obj/effect/proc_holder/spell/invoked/projectile/fireballgreater
#define SPELL_LIGHTNINGBOLT							/obj/effect/proc_holder/spell/invoked/projectile/lightningbolt
#define SPELL_SICKNESS								/obj/effect/proc_holder/spell/invoked/projectile/sickness
#define SPELL_SPITFIRE								/obj/effect/proc_holder/spell/invoked/projectile/spitfire
#define SPELL_SPLASH								/obj/effect/proc_holder/spell/invoked/projectile/splash
#define SPELL_PUSH_SPELL							/obj/effect/proc_holder/spell/invoked/push_spell
#define SPELL_RAISE_UNDEAD							/obj/effect/proc_holder/spell/invoked/raise_undead
#define SPELL_RAISE_UNDEAD_LESSER					/obj/effect/proc_holder/spell/invoked/raise_undead_lesser
#define SPELL_REPLENISH								/obj/effect/proc_holder/spell/invoked/replenish
#define SPELL_REVIVE								/obj/effect/proc_holder/spell/invoked/revive
#define SPELL_REVOKE_UNLIFE							/obj/effect/proc_holder/spell/invoked/revoke_unlife
#define SPELL_SACRED_FLAME_ROGUE					/obj/effect/proc_holder/spell/invoked/sacred_flame_rogue
#define SPELL_SEELIE_DUST							/obj/effect/proc_holder/spell/invoked/seelie_dust
#define SPELL_SHEPHERD								/obj/effect/proc_holder/spell/invoked/shepherd
#define SPELL_SLOWDOWN_SPELL_AOE					/obj/effect/proc_holder/spell/invoked/slowdown_spell_aoe
#define SPELL_STRENGTHEN_UNDEAD						/obj/effect/proc_holder/spell/invoked/strengthen_undead
#define SPELL_STRIP									/obj/effect/proc_holder/spell/invoked/strip
#define SPELL_SUMMON_BERRY							/obj/effect/proc_holder/spell/invoked/summon_berry
#define SPELL_SUMMON_RAT							/obj/effect/proc_holder/spell/invoked/summon_rat
#define SPELL_TEACH									/obj/effect/proc_holder/spell/invoked/teach
#define SPELL_VIGOROUSEXCHANGE						/obj/effect/proc_holder/spell/invoked/vigorousexchange
#define SPELL_BASIC_HEAL							/obj/effect/proc_holder/spell/self/basic_heal
#define SPELL_CLAWS									/obj/effect/proc_holder/spell/self/claws
#define SPELL_COMMAND_UNDEAD						/obj/effect/proc_holder/spell/self/command_undead
#define SPELL_CONVERT_ROLE_BOG						/obj/effect/proc_holder/spell/self/convertrole/bog
#define SPELL_CONVERT_ROLE_GUARD					/obj/effect/proc_holder/spell/self/convertrole/guard
#define SPELL_CONVERT_ROLE_MONK						/obj/effect/proc_holder/spell/self/convertrole/monk
#define SPELL_CONVERT_ROLE_PROSTITUTE				/obj/effect/proc_holder/spell/self/convertrole/prostitute
#define SPELL_CONVERT_ROLE_SERVANT					/obj/effect/proc_holder/spell/self/convertrole/servant
#define SPELL_CONVERT_ROLE_TEMPLAR					/obj/effect/proc_holder/spell/self/convertrole/templar
#define SPELL_GRANT_NOBILITY						/obj/effect/proc_holder/spell/self/grant_nobility
#define SPELL_GRANT_TITLE							/obj/effect/proc_holder/spell/self/grant_title
#define SPELL_HOWL									/obj/effect/proc_holder/spell/self/howl
#define SPELL_REBELCONVERT							/obj/effect/proc_holder/spell/self/rebelconvert
#define SPELL_TAP									/obj/effect/proc_holder/spell/self/tap
#define SPELL_TELLJOKE								/obj/effect/proc_holder/spell/self/telljoke
#define SPELL_TELLTRAGEDY							/obj/effect/proc_holder/spell/self/telltragedy
#define SPELL_SPACETIME_DIST						/obj/effect/proc_holder/spell/spacetime_dist
#define SPELL_AREA_TELEPORT							/obj/effect/proc_holder/spell/targeted/area_teleport/teleport
#define SPELL_AREA_TELEPORT_SANTA					/obj/effect/proc_holder/spell/targeted/area_teleport/teleport/santa
#define SPELL_BEASTTAME								/obj/effect/proc_holder/spell/invoked/beasttame
#define SPELL_BLESSCROP								/obj/effect/proc_holder/spell/targeted/blesscrop
#define SPELL_BURIALRITE							/obj/effect/proc_holder/spell/targeted/burialrite
#define SPELL_CHURN									/obj/effect/proc_holder/spell/targeted/churn
#define SPELL_CONJURE_VINES							/obj/effect/proc_holder/spell/targeted/conjure_vines
#define SPELL_CPR									/obj/effect/proc_holder/spell/targeted/cpr
#define SPELL_DEBRIDE								/obj/effect/proc_holder/spell/targeted/debride
#define SPELL_DOCHEAL								/obj/effect/proc_holder/spell/targeted/docheal
#define SPELL_EMPLOSION								/obj/effect/proc_holder/spell/targeted/emplosion
#define SPELL_DISABLE_TECH							/obj/effect/proc_holder/spell/targeted/emplosion/disable_tech
#define SPELL_ETHEREAL_JAUNT						/obj/effect/proc_holder/spell/targeted/ethereal_jaunt
#define SPELL_EXPLOSION								/obj/effect/proc_holder/spell/targeted/explosion
#define SPELL_MUTATE								/obj/effect/proc_holder/spell/targeted/genetic/mutate
#define SPELL_LICHDOM								/obj/effect/proc_holder/spell/targeted/lichdom
#define SPELL_MIND_TRANSFER							/obj/effect/proc_holder/spell/targeted/mind_transfer
#define SPELL_NIGHT_VISION							/obj/effect/proc_holder/spell/targeted/night_vision
#define SPELL_PERSONALITY_COMMUNE					/obj/effect/proc_holder/spell/targeted/personality_commune
#define SPELL_DUMBFIRE								/obj/effect/proc_holder/spell/targeted/projectile/dumbfire
#define SPELL_MAGIC_MISSILE							/obj/effect/proc_holder/spell/targeted/projectile/magic_missile
#define SPELL_PURGE									/obj/effect/proc_holder/spell/targeted/purge
#define SPELL_ROUSTAME								/obj/effect/proc_holder/spell/targeted/roustame
#define SPELL_SACRED_FLAME							/obj/effect/proc_holder/spell/targeted/sacred_flame
#define SPELL_SATE_CROP								/obj/effect/proc_holder/spell/targeted/sate_crop
#define SPELL_SEELIE_KISS							/obj/effect/proc_holder/spell/targeted/seelie_kiss
#define SPELL_SHADOWWALK							/obj/effect/proc_holder/spell/targeted/shadowwalk
#define SPELL_SHAPESHIFT							/obj/effect/proc_holder/spell/targeted/shapeshift
#define SPELL_SHAPE_SHIFT_BAT						/obj/effect/proc_holder/spell/targeted/shapeshift/bat
#define SPELL_SHAPE_SHIFT_BATFORM					/obj/effect/proc_holder/spell/targeted/shapeshift/bat/batform
#define SPELL_SHAPE_SHIFT_GASEOUSFORM				/obj/effect/proc_holder/spell/targeted/shapeshift/gaseousform
#define SPELL_SHAPE_SHIFT_GAS						/obj/effect/proc_holder/spell/targeted/shapeshift/gaseousform/gas
#define SPELL_SOURCE								/obj/effect/proc_holder/spell/targeted/shapeshift/source
#define SPELL_SMOKE									/obj/effect/proc_holder/spell/targeted/smoke
#define SPELL_SMOKE_LESSER							/obj/effect/proc_holder/spell/targeted/smoke/lesser
#define SPELL_SOULSPEAK								/obj/effect/proc_holder/spell/targeted/soulspeak
#define SPELL_STABLE								/obj/effect/proc_holder/spell/targeted/stable
#define SPELL_STATIC_ROOM							/obj/effect/proc_holder/spell/targeted/static_room
#define SPELL_SUMMONITEM							/obj/effect/proc_holder/spell/targeted/summonitem
#define SPELL_TESLA									/obj/effect/proc_holder/spell/targeted/tesla
#define SPELL_DARKVISION							/obj/effect/proc_holder/spell/targeted/touch/darkvision
#define SPELL_NONDETECTION							/obj/effect/proc_holder/spell/targeted/touch/nondetection
#define SPELL_PRESTIDIGITATION						/obj/effect/proc_holder/spell/targeted/touch/prestidigitation
#define SPELL_TRANSFIX								/obj/effect/proc_holder/spell/targeted/transfix
#define SPELL_TRANSFIX_MASTER						/obj/effect/proc_holder/spell/targeted/transfix/master
#define SPELL_BLIND									/obj/effect/proc_holder/spell/targeted/trigger/blind
#define SPELL_TURF_TELEPORT							/obj/effect/proc_holder/spell/targeted/turf_teleport
#define SPELL_BLINK									/obj/effect/proc_holder/spell/targeted/turf_teleport/blink
#define SPELL_BLINK_CULT							/obj/effect/proc_holder/spell/targeted/turf_teleport/blink/cult
#define SPELL_VAMP_REJUV							/obj/effect/proc_holder/spell/targeted/vamp_rejuv
#define SPELL_VOICE_OF_GOD							/obj/effect/proc_holder/spell/voice_of_god
#define SPELL_VOICE_OF_GOD_CLOWN					/obj/effect/proc_holder/spell/voice_of_god/clown
#define SPELL_METEOR								/obj/effect/proc_holder/spell/invoked/meteor_storm
#define SPELL_SUNDER_LIGHTNING						/obj/effect/proc_holder/spell/invoked/sundering_lightning
#define SPELL_FROSTBOLT								/obj/effect/proc_holder/spell/invoked/projectile/frostbolt
#define SPELL_LIGHTNINGLURE							/obj/effect/proc_holder/spell/targeted/lightninglure
#define SPELL_ARCYNE_STORM							/obj/effect/proc_holder/spell/invoked/arcyne_storm
#define SPELL_SUMMON_WEAPON							/obj/effect/proc_holder/spell/targeted/summonweapon
#define SPELL_MENDING								/obj/effect/proc_holder/spell/invoked/mending
#define SPELL_REPEL									/obj/effect/proc_holder/spell/invoked/projectile/repel
