#define COMSIG_VICIOUSLY_MOCKED "viciously_mocked_act" // from base of /obj/effect/proc_holder/spell/invoked/mockery/cast() (victim)
#define COMSIG_LUX_EXTRACTED "lux_extracted" // from base of /datum/surgery_step/extract_lux/success() (victim)
#define COMSIG_DRUG_SNIFFED "drug_sniffed" // from base of /obj/item/reagent_containers/powder/attack() (applier)
#define COMSIG_ITEM_STOLEN "item_stolen" // from base of /mob/living/MiddleClickOn() (victim)
#define COMSIG_SKILL_RANK_INCREASED "skill_rank_increased" // from base of adjust_skillrank() (skill_type, new_rank)
#define COMSIG_ITEM_CRAFTED "item_crafted" // from base of /atom/proc/OnCrafted() (user, craft_path)
#define COMSIG_ORGAN_CONSUMED "organ_consumed" // from base of /obj/item/reagent_containers/food/snacks/organ/on_consume() (mob/living/consumer, organ_type)
#define COMSIG_TORTURE_PERFORMED "torture_performed" // from base of /mob/living/carbon/human/proc/torture_victim() (mob/living/torturer, mob/living/victim)
#define COMSIG_GRAVE_CONSECRATED "grave_consecrated" // from base of /obj/structure/gravemarker/OnCrafted() (mob/living/consecrator, obj/container)
#define COMSIG_ANIMAL_TAMED "animal_tamed" // from base of /mob/living/simple_animal/proc/tamed() (mob/living/tamer, mob/living/simple_animal)
#define COMSIG_MOB_HUGGED "mob_hugged" // from base of /datum/emote/living/hug/adjacentaction() (target)
#define COMSIG_GLOBAL_FISH_RELEASED "global_fish_released" // from base of /turf/open/water/Entered() (fish_type, fish_rarity)
#define COMSIG_ABYSSOID_CREATED "abyssoid_created" // from base of /obj/effect/proc_holder/spell/self/create_abyssoid/cast() ()
#define COMSIG_ROTTEN_FOOD_EATEN "rotten_food_eaten" // from base of /obj/item/reagent_containers/food/snacks/on_consume() (/obj/item/reagent_containers/food/snacks/eaten_food)
#define COMSIG_LUX_TASTED "lux_tasted" // from base of /datum/status_effect/buff/lux_drank/on_apply() ()
#define COMSIG_HEAD_PUNCHED "head_punched" // from base of //mob/living/carbon/monkey/attack_hand() (victim)
#define COMSIG_TREE_TRANSFORMED "tree_transformed" // from base of /obj/effect/proc_holder/spell/invoked/transform_tree/cast() ()
#define COMSIG_GLOB_ROLE_CONVERTED "role_converted" // from base of /obj/effect/proc_holder/spell/self/convertrole/proc/convert() (mob/living/carbon/human/recruiter, mob/living/carbon/human/recruit, newrole)
