#define OMEN_ROUNDSTART "roundstart"
#define OMEN_NOLORD "nolord"
#define OMEN_NOPRIEST "nopriest"
#define OMEN_NOBLEDEATH "nobledeath"
#define OMEN_SUNSTEAL "sunsteal"
#define OMEN_SKELETONSIEGE "skeletonsiege"

#define OMEN_DESECRATE_PSYDON "desecrate_psydon"
#define OMEN_DESECRATE_ASTRATA "desecrate_astrata"
#define OMEN_DESECRATE_NOC "desecrate_noc"
#define OMEN_DESECRATE_DENDOR "desecrate_dendor"
#define OMEN_DESECRATE_ABYSSOR "desecrate_abbyssor"
#define OMEN_DESECRATE_RAVOX "desecrate_ravox"
#define OMEN_DESECRATE_NECRA "desecrate_necra"
#define OMEN_DESECRATE_XYLIX "desecrate_xylix"
#define OMEN_DESECRATE_PESTRA "desecrate_pestra"
#define OMEN_DESECRATE_MALUM "desecrate_malum"
#define OMEN_DESECRATE_EORA "desecrate_eora"
