//#define SLEEP_EXP_NOVICE 100
//#define SLEEP_EXP_APPRENTICE 150
//#define SLEEP_EXP_JOURNEYMAN 250
//#define SLEEP_EXP_EXPERT 400
//#define SLEEP_EXP_MASTER 600
//#define SLEEP_EXP_LEGENDARY 1000

#define SLEEP_EXP_NOVICE 50
#define SLEEP_EXP_APPRENTICE 75
#define SLEEP_EXP_JOURNEYMAN 150
#define SLEEP_EXP_EXPERT 300
#define SLEEP_EXP_MASTER 500
#define SLEEP_EXP_LEGENDARY 700
