//#define SLEEP_EXP_NOVICE 100
//#define SLEEP_EXP_APPRENTICE 150
//#define SLEEP_EXP_JOURNEYMAN 250
//#define SLEEP_EXP_EXPERT 400
//#define SLEEP_EXP_MASTER 600
//#define SLEEP_EXP_LEGENDARY 1000

#define SLEEP_EXP_NOVICE 100
#define SLEEP_EXP_APPRENTICE 100
#define SLEEP_EXP_JOURNEYMAN 100
#define SLEEP_EXP_EXPERT 100
#define SLEEP_EXP_MASTER 100
#define SLEEP_EXP_LEGENDARY 100
