#define SLEEP_EXP_NOVICE 40
#define SLEEP_EXP_APPRENTICE 65
#define SLEEP_EXP_JOURNEYMAN 125
#define SLEEP_EXP_EXPERT 160
#define SLEEP_EXP_MASTER 220
#define SLEEP_EXP_LEGENDARY 350

#define BASE_DREAM_DUST 100
#define DREAM_DUST_PER_INT 25

#define INSPIRATION_MAX_SKILL_LEVEL 2

#define STRESS_THRESHOLD_NICE 1
#define STRESS_THRESHOLD_GOOD 2
#define STRESS_THRESHOLD_NEUTRAL 3
#define STRESS_THRESHOLD_STRESSED 4
#define STRESS_THRESHOLD_STRESSED_BAD 5
#define STRESS_THRESHOLD_FREAKING_OUT 6
