#define DRAGON_ATTACK_SPEED (CLICK_CD_MELEE * 0.9)
#define DRAGON_BROODMOTHER_ATTACK_SPEED (CLICK_CD_MELEE * 0.9)

#define DRAGGER_ATTACK_SPEED (CLICK_CD_MELEE)
#define HAUNT_ATTACK_SPEED (CLICK_CD_MELEE)
#define HONEYSPIDER_ATTACK_SPEED (CLICK_CD_MELEE * 1.1)

#define MINOTAUR_ATTACK_SPEED (CLICK_CD_MELEE)
#define MINOTAUR_AXE_ATTACK_SPEED (CLICK_CD_MELEE)

#define MOLE_ATTACK_SPEED (CLICK_CD_MELEE)
#define MOSSBACK_ATTACK_SPEED (CLICK_CD_MELEE)
#define MUDCRAB_ATTACK_SPEED (CLICK_CD_MELEE * 1.5) // doesn't work 
#define ORC_ATTACK_SPEED (CLICK_CD_MELEE)
#define RAT_ATTACK_SPEED (CLICK_CD_MELEE * 1.1)

#define TROLL_ATTACK_SPEED (CLICK_CD_MELEE * 0.9)
#define TROLLBOG_ATTACK_SPEED (CLICK_CD_MELEE * 0.9)

#define WOLF_ATTACK_SPEED (CLICK_CD_MELEE * 1.1) 
