//Putting everything here because the creature code is everywhere

#define DRAGON_BROODMOTHER_HEALTH 1600
#define DRAGON_HEALTH 800

#define DRAGGER_HEALTH 215

#define HAUNT_HEALTH 50
#define HONEYSPIDER_HEALTH 65

#define MINOTAUR_AXE_HEALTH 600
#define MINOTAUR_HEALTH 600
#define MOLE_HEALTH 340
#define MOSSBACK_HEALTH 200
#define MUDCRAB_HEALTH 40

#define ORC_HEALTH 100

#define RAT_HEALTH 65

#define SKELETON_HEALTH 100

#define TROLL_HEALTH 350
#define TROLLBOG_HEALTH 350

#define WOLF_HEALTH 120 
#define DEEPONE_HEALTH 140
