//By default, CLICK_CD_MELEE 12 deciseconds (1.2 seconds). Everything scales from that. 
// A higher value means they attack more slowly and lower means more quickly

#define DRAGON_ATTACK_SPEED (CLICK_CD_MELEE * 0.9)
#define DRAGON_BROODMOTHER_ATTACK_SPEED (CLICK_CD_MELEE * 0.9)

#define DRAGGER_ATTACK_SPEED (CLICK_CD_MELEE)
#define HAUNT_ATTACK_SPEED (CLICK_CD_MELEE)
#define HONEYSPIDER_ATTACK_SPEED (CLICK_CD_MELEE * 1.1)
#define MIRESPIDER_ATTACK_SPEED (CLICK_CD_MELEE * 1.1)
#define ARAGN_ATTACK_SPEED (CLICK_CD_MELEE * 1.1)
#define MIRESPIDER_LURKER_ATTACK_SPEED (CLICK_CD_MELEE * 0.8)

#define MINOTAUR_ATTACK_SPEED (CLICK_CD_MELEE * 0.9)
#define MINOTAUR_AXE_ATTACK_SPEED (CLICK_CD_MELEE)

#define MOLE_ATTACK_SPEED (CLICK_CD_MELEE)
#define MOSSBACK_ATTACK_SPEED (CLICK_CD_MELEE)
#define MUDCRAB_ATTACK_SPEED (CLICK_CD_MELEE * 1.5) // crabs don't have an attack
#define ORC_ATTACK_SPEED (CLICK_CD_MELEE)
#define RAT_ATTACK_SPEED (CLICK_CD_MELEE * 1.2)
#define SAIGA_ATTACK_SPEED (CLICK_CD_MELEE * 1.1) // Saiga should attack at a moderate speed

#define SKELETON_ATTACK_SPEED (CLICK_CD_MELEE)

#define TROLL_ATTACK_SPEED (CLICK_CD_MELEE * 0.9)
#define TROLLBOG_ATTACK_SPEED (CLICK_CD_MELEE * 0.9)

#define WOLF_ATTACK_SPEED (CLICK_CD_MELEE * 1.1) 
#define DEEPONE_ATTACK_SPEED (CLICK_CD_MELEE * 1.75)
#define MINOR_DREAMFIEND_ATTACK_SPEED (CLICK_CD_MELEE * 1.1)
#define MAJOR_DREAMFIEND_ATTACK_SPEED (CLICK_CD_MELEE)
#define ANCIENT_DREAMFIEND_ATTACK_SPEED (CLICK_CD_MELEE * 0.9)
